GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/63e6a55fd401277006acfb38

###

GET http://localhost:3001/api/notes/63

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VSC REST Client is good in testing backend",
    "important": true
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "important": true
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
}

###

DELETE http://localhost:3001/api/notes/63e7790f00b8233ff11bfbe8

###

PUT http://localhost:3001/api/notes/63e6a55fd401277006acfb38
Content-Type: application/json

{
    "content": "Tätä viestiä on editoitu VSC REST Clientin kautta",
    "important": false
}